MIN_ENGINE_VERSION = [1, 20, 0]
PORTER_TAG = "Ported with Zarya Porter by Choui"

FORMAT_TABLE = {
    1: ("1.6.1 - 1.8.9", True),
    2: ("1.9 - 1.10.2", False),
    3: ("1.11 - 1.12.2", False),
    4: ("1.13 - 1.14.4", False),
    5: ("1.15 - 1.16.1", False),
    6: ("1.16.2 - 1.16.5", False),
    7: ("1.17 - 1.17.1", False),
    8: ("1.18 - 1.18.2", False),
    9: ("1.19 - 1.19.2", False),
    10: ("1.19.3 snapshots", False),
    11: ("1.19.3", False),
    12: ("1.19.4", False),
    13: ("1.20 snapshots", False),
    14: ("1.20 snapshots", False),
    15: ("1.20 - 1.20.1", False),
    16: ("1.20.2 snapshots", False),
    17: ("1.20.2 snapshots", False),
    18: ("1.20.2", False),
    19: ("1.20.3 snapshots", False),
    20: ("1.20.3 snapshots", False),
    21: ("1.20.3 snapshots", False),
    22: ("1.20.3 - 1.20.4", False),
    23: ("1.20.4 snapshots", False),
    24: ("1.20.4 snapshots", False),
    25: ("1.20.4 snapshots", False),
    26: ("1.20.4 snapshots", False),
    27: ("1.20.4 snapshots", False),
    28: ("1.20.5 snapshots", False),
    29: ("1.20.5 snapshots", False),
    30: ("1.20.5 snapshots", False),
    31: ("1.20.5 snapshots", False),
    32: ("1.20.5 - 1.20.6", False),
    33: ("1.21 snapshots", False),
    34: ("1.21 - 1.21.1", False),
    35: ("1.21.2 snapshots", False),
    36: ("1.21.2 snapshots", False),
    37: ("1.21.2 snapshots", False),
    38: ("1.21.2 snapshots", False),
    39: ("1.21.2 snapshots", False),
    40: ("1.21.2 snapshots", False),
    41: ("1.21.2 snapshots", False),
    42: ("1.21.2 - 1.21.3", False),
    43: ("1.21.4 snapshots", False),
    44: ("1.21.4 snapshots", False),
    45: ("1.21.4 snapshots", False),
    46: ("1.21.4", False),
    47: ("1.21.5 snapshots", False),
    48: ("1.21.5 snapshots", False),
    49: ("1.21.5 snapshots", False),
    50: ("1.21.5 snapshots", False),
    51: ("1.21.5 snapshots", False),
    52: ("1.21.5 snapshots", False),
    53: ("1.21.5 snapshots", False),
    54: ("1.21.5 snapshots", False),
    55: ("1.21.5", False),
    56: ("1.21.6 snapshots", False),
    57: ("1.21.6", False),
    58: ("1.21.7 snapshots", False),
    59: ("1.21.7 snapshots", False),
    60: ("1.21.7 snapshots", False),
    61: ("1.21.7 snapshots", False),
    62: ("1.21.7 snapshots", False),
    63: ("1.21.7 snapshots", False),
    64: ("1.21.7 - 1.21.8", False),
    65: ("1.21.9 snapshots", False),
    66: ("1.21.9 snapshots", False),
    67: ("1.21.9 snapshots", False),
    68: ("1.21.9 snapshots", False),
    69: ("1.21.9 - 1.21.10", False),
}

VERSION_FINGERPRINTS = [
    ("1.21.9+", ["entity/copper_golem", "block/copper_chest", "block/copper_bars", "block/copper_lantern", "block/shelf_", "item/copper_nugget"]),
    ("1.21.6 - 1.21.8", ["entity/ghast/happy_ghast", "block/dried_ghast", "item/harness"]),
    ("1.21.5", ["block/leaf_litter", "block/firefly_bush", "block/bush", "block/cactus_flower", "block/wildflowers", "block/short_dry_grass", "block/tall_dry_grass"]),
    ("1.21.4", ["block/pale_oak_", "block/creaking_heart", "block/open_eyeblossom", "block/closed_eyeblossom", "entity/creaking"]),
    ("1.21.2 - 1.21.3", ["entity/equipment/"]),
    ("1.21 - 1.21.1", ["item/mace", "block/crafter_", "block/vault_", "entity/trial_spawner", "block/trial_spawner", "entity/breeze", "block/chiseled_tuff"]),
    ("1.20.5 - 1.20.6", ["item/wolf_armor", "entity/armadillo", "item/breeze_rod", "item/wind_charge"]),
    ("1.20 - 1.20.1", ["block/cherry_", "block/pink_petals", "entity/sniffer", "entity/camel", "item/music_disc_relic", "block/bamboo_planks", "block/suspicious_", "item/bamboo_raft"]),
    ("1.19 - 1.19.2", ["block/mud", "block/mangrove_", "block/packed_mud", "block/sculk", "entity/allay", "entity/frog", "entity/warden", "entity/tadpole", "block/reinforced_deepslate"]),
    ("1.18 - 1.18.2", ["item/music_disc_otherside"]),
    ("1.17 - 1.17.1", ["block/copper_", "block/amethyst_", "block/deepslate", "block/candle", "entity/axolotl", "entity/glow_squid", "item/spyglass", "item/glow_ink_sac", "block/dripstone_", "block/moss_block", "block/big_dripleaf", "block/small_dripleaf", "block/spore_blossom", "block/azalea", "block/calcite", "block/tuff", "block/rooted_dirt", "block/raw_iron", "block/raw_gold", "block/raw_copper", "block/hanging_roots"]),
    ("1.16.2 - 1.16.5", ["block/crying_obsidian", "block/netherite_block", "item/netherite_", "block/target_", "block/soul_fire_", "entity/piglin", "entity/hoglin", "entity/zoglin", "block/ancient_debris", "block/crimson_", "block/warped_", "block/shroomlight", "block/nether_gold_ore", "block/basalt_", "block/blackstone", "entity/strider", "item/music_disc_pigstep", "block/twisting_vines", "block/warped_wart_block", "block/lodestone_", "entity/zombified_piglin"]),
    ("1.16 - 1.16.1", ["block/crying_obsidian", "block/netherite_block", "item/netherite_", "block/target_", "block/soul_fire_", "entity/piglin", "entity/hoglin", "block/ancient_debris", "block/crimson_", "block/warped_", "block/shroomlight", "block/basalt_", "block/blackstone", "entity/strider", "item/music_disc_pigstep"]),
    ("1.15 - 1.15.2", ["entity/bee", "block/honey_block_", "block/beehive_", "item/honeycomb", "block/honeycomb_block", "block/bee_nest_"]),
    ("1.14 - 1.14.4", ["item/crossbow_", "entity/fox", "block/barrel_", "block/lectern", "block/sweet_berry_bush", "block/composter", "block/campfire", "entity/panda", "entity/pillager", "entity/ravager", "entity/villager/villager", "block/smoker", "block/loom_", "block/stonecutter", "block/bamboo_stalk", "block/scaffolding_"]),
    ("1.13 - 1.13.2", ["entity/fish/", "item/trident", "block/dried_kelp_", "item/turtle_helmet", "block/conduit", "block/blue_ice", "block/sea_pickle", "block/turtle_egg", "block/coral_", "block/dead_coral", "block/bubble_column"]),
    ("1.12 - 1.12.2", ["entity/parrot/", "blocks/concrete_", "blocks/glazed_terracotta_", "blocks/concrete_powder_"]),
    ("1.11 - 1.11.2", ["entity/llama", "blocks/observer", "items/totem", "entity/evocation_illager", "entity/vex", "items/iron_nugget"]),
    ("1.10 - 1.10.2", ["entity/polarbear", "blocks/magma", "blocks/nether_wart_block", "blocks/bone_block", "entity/stray", "entity/husk", "blocks/red_nether_brick"]),
    ("1.9 - 1.9.4", ["entity/end_crystal", "items/elytra", "entity/shield_base", "blocks/end_rod", "blocks/purpur_", "blocks/grass_path_side", "items/chorus_fruit", "blocks/chorus_", "entity/shulker/shulker", "blocks/end_bricks", "blocks/frosted_ice_", "items/dragon_breath", "items/spectral_arrow", "blocks/structure_block"]),
    ("1.8 - 1.8.9", ["blocks/stone_granite", "blocks/slime", "blocks/prismarine_", "blocks/red_sandstone", "blocks/iron_trapdoor", "blocks/coarse_dirt", "entity/guardian", "entity/rabbit/", "blocks/sea_lantern", "entity/armorstand", "items/banner_base", "entity/end_crystal_crystal"]),
    ("1.7.x", ["blocks/ice_packed", "items/fish_cod_raw", "blocks/planks_acacia", "blocks/planks_dark_oak", "blocks/double_plant_paeonia", "blocks/glass_", "blocks/leaves_acacia", "blocks/leaves_big_oak"]),
    ("1.6.x", ["blocks/coal_block", "blocks/hay_block_", "blocks/hardened_clay", "entity/horse/donkey", "items/diamond_horse_armor"]),
]

ICONS_SLICES = [
    ("cross_hair", (0, 0, 16, 16), 16, 16, None),
    ("heart_background", (16, 0, 9, 9), 9, 9, None),
    ("heart", (52, 0, 9, 9), 9, 9, None),
    ("heart_half", (61, 0, 9, 9), 9, 9, None),
    ("armor_empty", (16, 9, 9, 9), 9, 9, None),
    ("armor_half", (25, 9, 9, 9), 9, 9, None),
    ("armor_full", (34, 9, 9, 9), 9, 9, None),
    ("bubbles_empty", (16, 18, 9, 9), 9, 9, None),
    ("bubbles_full", (25, 18, 9, 9), 9, 9, None),
    ("bubble_pop", (34, 18, 9, 9), 9, 9, None),
    ("hunger_background", (16, 27, 9, 9), 9, 9, None),
    ("hunger_full", (52, 27, 9, 9), 9, 9, None),
    ("hunger_half", (61, 27, 9, 9), 9, 9, None),
]

HUD_COPIES = {
    "hunger_full": ["hunger_effect_full"],
    "hunger_half": ["hunger_effect_half"],
    "hunger_background": ["hunger_effect_background"],
}

HOTBAR_SLOTS = 9
HOTBAR_X0 = 1
HOTBAR_SLOT_W = 20
HOTBAR_H = 22
HOTBAR_Y = 0
SELECTED_SLOT = (0, 22, 24, 23)
SELECTED_CANVAS = (24, 24)

XP_EMPTY_BOX = (0, 64, 182, 5)
XP_FULL_BOX = (0, 69, 182, 5)
XP_EMPTY_NINESLICE = [6, 1, 6, 1]
XP_FULL_NINESLICE = [1, 0, 1, 0]

CONTAINER_TEXTURES = [
    "inventory",
    "crafting_table",
    "furnace",
    "generic_54",
    "dispenser",
    "hopper",
    "brewing_stand",
    "anvil",
    "enchanting_table",
]

EXTRA_BLOCK_COPIES = {
    "water_still": ["water_still_grey"],
    "water_flow": ["water_flow_grey"],
    "fire_0": ["flame_atlas"],
}

CORAL_COLORS = {
    "tube": "blue",
    "brain": "pink",
    "bubble": "purple",
    "fire": "red",
    "horn": "yellow",
}

FLOWERS = {
    "dandelion": "flower_dandelion",
    "poppy": "flower_rose",
    "blue_orchid": "flower_blue_orchid",
    "allium": "flower_allium",
    "azure_bluet": "flower_houstonia",
    "red_tulip": "flower_tulip_red",
    "orange_tulip": "flower_tulip_orange",
    "white_tulip": "flower_tulip_white",
    "pink_tulip": "flower_tulip_pink",
    "oxeye_daisy": "flower_houstonia",
    "cornflower": "flower_cornflower",
    "lily_of_the_valley": "flower_lily_of_the_valley",
    "wither_rose": "flower_wither_rose",
    "sunflower": "double_plant_sunflower",
    "lilac": "double_plant_syringa",
    "rose_bush": "double_plant_rose",
    "peony": "double_plant_paeonia",
    "short_grass": "tallgrass",
    "grass": "tallgrass",
    "seagrass": "seagrass",
}

COLORS = ["white", "orange", "magenta", "light_blue", "yellow", "lime", "pink",
          "gray", "light_gray", "cyan", "purple", "blue", "brown", "green", "red", "black"]

LEGACY_EFFECTS = {
    "move_speed": "speed",
    "move_slowdown": "slowness",
    "dig_speed": "haste",
    "dig_slowdown": "mining_fatigue",
    "damage_boost": "strength",
    "heal": "instant_health",
    "harm": "instant_damage",
    "jump": "jump_boost",
    "confusion": "nausea",
    "regeneration": "regeneration",
    "damage_resistance": "resistance",
    "fire_resistance": "fire_resistance",
    "water_breathing": "water_breathing",
    "invisibility": "invisibility",
    "blindness": "blindness",
    "night_vision": "night_vision",
    "hunger": "hunger",
    "weakness": "weakness",
    "poison": "poison",
    "wither": "wither",
    "health_boost": "health_boost",
    "absorption": "absorption",
    "saturation": "saturation",
    "luck": "luck",
    "bad_luck": "unluck",
    "levitation": "levitation",
    "glowing": "glowing",
}

SOUND_CATEGORIES = {
    "music": "music",
    "record": "record",
    "weather": "weather",
    "block": "block",
    "player": "player",
    "ui": "ui",
    "ambient": "ambient",
}

HOSTILE_ENTITIES = {
    "blaze", "bogged", "breeze", "cave_spider", "creeper", "drowned", "elder_guardian",
    "enderman", "endermite", "evoker", "ghast", "guardian", "hoglin", "husk", "magma_cube",
    "phantom", "piglin", "piglin_brute", "pillager", "ravager", "shulker", "silverfish",
    "skeleton", "skeleton_horse", "slime", "spider", "stray", "strider", "vex",
    "vindicator", "warden", "witch", "wither", "wither_skeleton", "zoglin", "zombie",
    "zombie_horse", "zombie_villager", "zombified_piglin", "creaking",
}

EGG_NAMES = {
    "elder_guardian": "elderguardian",
    "zombie_pigman": "pigzombie",
    "zombified_piglin": "pigzombie",
    "mooshroom": "mushroomcow",
    "magma_cube": "lava_slime",
    "skeleton_horse": "skeletonhorse",
    "zombie_horse": "zombiehorse",
    "zombie_villager": "zombievillager",
    "wandering_trader": "wanderingtrader",
    "tropical_fish": "clownfish",
    "polar_bear": "polarbear",
    "mountain_goat": "goat",
}

BLOCK_SPECIAL = {
    "anvil": ["anvil_base"],
    "anvil_top": ["anvil_top_damaged_0"],
    "chipped_anvil_top": ["anvil_top_damaged_1"],
    "damaged_anvil_top": ["anvil_top_damaged_2"],
    "rail": ["rail"],
    "rail_corner": ["rail_turn"],
    "powered_rail": ["rail_golden"],
    "powered_rail_on": ["rail_golden_powered"],
    "detector_rail": ["rail_detector"],
    "detector_rail_on": ["rail_detector_powered"],
    "activator_rail": ["rail_activator"],
    "activator_rail_on": ["rail_activator_powered"],
    "carved_pumpkin": ["pumpkin_face"],
    "redstone_dust_dot": ["redstone_dust_cross"],
    "redstone_dust_line0": ["redstone_dust_line"],
    "attached_melon_stem": ["melon_stem_connected"],
    "melon_stem": ["melon_stem_disconnected"],
    "attached_pumpkin_stem": ["pumpkin_stem_connected"],
    "pumpkin_stem": ["pumpkin_stem_disconnected"],
    "mossy_cobblestone": ["cobblestone_mossy"],
    "smooth_stone": ["stone"],
    "stone_bricks": ["stonebrick"],
    "chiseled_stone_bricks": ["stonebrick_chiseled"],
    "cracked_stone_bricks": ["stonebrick_cracked"],
    "mossy_stone_bricks": ["stonebrick_mossy"],
    "chiseled_nether_bricks": ["nether_brick_chiseled"],
    "cracked_nether_bricks": ["nether_brick_cracked"],
    "chiseled_quartz_block": ["quartz_chiseled"],
    "smooth_sandstone": ["sandstone_smooth"],
    "chiseled_sandstone": ["sandstone_carved"],
    "cut_sandstone": ["sandstone_smooth"],
    "smooth_red_sandstone": ["red_sandstone_smooth"],
    "chiseled_red_sandstone": ["red_sandstone_carved"],
    "cut_red_sandstone": ["red_sandstone_smooth"],
    "granite": ["stone_granite"],
    "polished_granite": ["stone_granite_smooth"],
    "diorite": ["stone_diorite"],
    "polished_diorite": ["stone_diorite_smooth"],
    "andesite": ["stone_andesite"],
    "polished_andesite": ["stone_andesite_smooth"],
    "grass_block_top": ["grass_top", "grass_carried"],
    "grass_block_side": ["grass_side"],
    "grass_block_side_overlay": ["grass_side_overlay"],
    "grass_block_snow": ["grass_side_snow"],
    "dirt_path_top": ["grass_path_top"],
    "dirt_path_side": ["grass_path_side"],
    "frosted_ice": ["frosted_ice_0"],
    "cobweb": ["web"],
    "spawner": ["mob_spawner"],
    "farmland": ["farmland_wet", "farmland_dry"],
    "torchflower_crop_stage0": ["torchflower_stage0"],
    "open_eyeblossom": ["eyeblossom_blooming"],
    "closed_eyeblossom": ["eyeblossom_dormant"],
    "torch": ["torch_on", "torch"],
    "redstone_torch": ["redstone_torch_on", "redstone_torch_off"],
}

ITEM_SPECIAL = {
    "beef": ["beef_raw"],
    "cooked_beef": ["beef_cooked"],
    "chicken": ["chicken_raw"],
    "cooked_chicken": ["chicken_cooked"],
    "porkchop": ["porkchop_raw"],
    "cooked_porkchop": ["porkchop_cooked"],
    "rabbit": ["rabbit_raw"],
    "cooked_rabbit": ["rabbit_cooked"],
    "mutton": ["mutton_raw"],
    "cooked_mutton": ["mutton_cooked"],
    "cod": ["fish_cod_raw", "fish_cod", "cod"],
    "salmon": ["fish_salmon_raw", "fish_salmon", "salmon"],
    "tropical_fish": ["fish_clownfish", "clownfish", "fish_tropical_raw"],
    "pufferfish": ["fish_pufferfish_raw", "pufferfish"],
    "water_bucket": ["bucket_water"],
    "lava_bucket": ["bucket_lava"],
    "milk_bucket": ["bucket_milk"],
    "powder_snow_bucket": ["bucket_powder_snow"],
    "cod_bucket": ["bucket_cod"],
    "salmon_bucket": ["bucket_salmon"],
    "tropical_fish_bucket": ["bucket_tropical"],
    "pufferfish_bucket": ["bucket_pufferfish"],
    "axolotl_bucket": ["bucket_axolotl"],
    "tadpole_bucket": ["bucket_tadpole"],
    "bucket": ["bucket_empty"],
    "oak_door": ["door_wood"],
    "iron_door": ["door_iron"],
    "book": ["book_normal"],
    "writable_book": ["book_writable"],
    "written_book": ["book_written"],
    "enchanted_book": ["book_enchanted"],
    "bow": ["bow_standby"],
    "crossbow": ["crossbow_standby"],
    "potion": ["potion_bottle_drinkable"],
    "splash_potion": ["potion_bottle_splash"],
    "lingering_potion": ["potion_bottle_lingering"],
    "filled_map": ["map_filled"],
    "map": ["map_empty"],
    "golden_apple": ["apple_golden"],
    "enchanted_golden_apple": ["apple_golden_enchanted", "apple_golden"],
    "oak_sign": ["sign"],
    "bamboo_raft": ["boat_bamboo", "boat_oak"],
    "camel_husk_spawn_egg": ["egg_camel_husk"],
}
